version: '3.8'
services:
    postgres:
        container_name: "airflow_postgres"
        image: postgres:9.6
        env_file:
            - .env
    scheduler:
        container_name: "airflow_scheduler"
        build:
            context: ./docker/airflow
        image: apache/airflow_custom:latest
        command: scheduler
        restart: on-failure
        depends_on:
            - postgres
        env_file:
            - .env
        volumes:
            - ./airflow/dags:/opt/airflow/dags
            - ./airflow/plugins:/opt/airflow/plugins
            - ./airflow/logs:/opt/airflow/logs
    webserver:
        container_name: "airflow_webserver"
        build:
            context: ./docker/airflow
        image: apache/airflow_custom:latest
        entrypoint: ./scripts/entrypoint.sh
        restart: always
        depends_on:
            - postgres
            - scheduler
        env_file:
            - .env
        volumes:
            - ./airflow/dags:/opt/airflow/dags
            - ./airflow/plugins:/opt/airflow/plugins
            - ./airflow/logs:/opt/airflow/logs
            - ./scripts/airflow_webserver:/opt/airflow/scripts
        ports:
            - "8080:8080"
    mongodb:
        container_name: "mongodb"
        build: ./docker/db
        env_file:
            - .env
        restart: always
        ports:
            - "27017:27017"